### PR TITLE
December updates

### PR DESCRIPTION
**Pull request by StevenCannon-USDA**
Many changes. The most consequential ones:

- The new search forms and buttons on the home page
- Changed nav item "taxa" to "genomics"
- Merged content from "genomes" into "genomics" page
- Added a blog post
- Added content for a community page (work is still needed there)
- Copied presentations and meeting agendas to the Datastore annex
- Added assembly comparison images, for /genomics/peanut_genome_v1_v2.html, to the Datastore annex
- Moved some applications into iframes: sequenceserver, gcvit, funnotate
- Updated search code to use current web components in the theme
- Consolidated tools into tools/

For other changes, see the list of commits.

Some remaining to-do items:

- /tools/search/trait.html is not functioning correctly
- Add specific resource links in the community page
- Make a dedicated browsers page, similar to https://www.soybase.org/tools/browsers/

### CODE REVIEW

**Comment by sdash-github** [comment]
@adf-ncgr:   :Did this affect https://dev.peanutbase.org/ ? It shows 503 error.
@StevenCannon-USDA :  Is this branch visible in one of your dev-site to look at?

**Comment by adf-ncgr** [comment]
I'm in the middle of tussling with dev-pb-jekyll upgrades, it's going to be flaky for a while

**Review by sdash-github — APPROVED** [review]
Review and approval points:
* Let us move forward with these changes: merge and the changes be visible. 
* It is in line with SoyBase and LIS interface where necessary and hence desirable. 
* We can gradually do additions/modifications/alterations as necessary after these updates are incorporated.

**Comment by StevenCannon-USDA** [comment]
> Review and approval points:
> 
> * Let us move forward with these changes: merge and the changes be visible.
> * It is in line with SoyBase and LIS interface where necessary and hence desirable.
> * We can gradually do additions/modifications/alterations as necessary after these updates are incorporated.

@sdash-github Thanks; I don't disagree. Move fast, break things, fix things :-)
I'll go ahead with the merge.

Incidentally, I am not using a public dev instance, but am doing the development and testing on my machine, using 
`bundle exec jekyll serve --incremental --livereload --livereload_port 35729 --port 4002`
from the Makefile.

If there is another workflow for Peanutbase development / review / production, I'll need to get instructions.

**Comment by sdash-github** [comment]
Once github, jekyll-peanutbase,  is updated with your changes, I will pull it to dev.peanutbase.org and then have a quick check of the functionality of the site. Will also add a news item of these updates.
Then I will also pull it to production. 
So, as long as jekyll-peanutbase repo is updated by you, that should be all from your side.

**Comment by adf-ncgr** [comment]
dev-pb-jekyll should be back so feel free to pull the changes there when you're ready

**Comment by sdash-github** [comment]
### Submodule_theme Error during git pull:
(For @adf-ncgr  to look at)
May be relevant:
"In sufficient permission...", could it be due to some files are root owned. This dir is mostly and should be with developer group permission.


```[sdash@dev-pb-jekyll /var/www/jekyll-peanutbase]
<$> git fetch --dry-run
remote: Enumerating objects: 204, done.
remote: Counting objects: 100% (204/204), done.
remote: Compressing objects: 100% (94/94), done.
remote: Total 167 (delta 65), reused 162 (delta 61), pack-reused 0 (from 0)
Receiving objects: 100% (167/167), 1.32 MiB | 4.18 MiB/s, done.
Resolving deltas: 100% (65/65), completed with 21 local objects.
From https://github.com/PeanutBase/jekyll-peanutbase
   923f7bb..71ab125  main       -> origin/main
Fetching submodule _themes/jekyll-theme-legumeinfo
error: insufficient permission for adding an object to repository database ./objects
fatal: failed to write object
fatal: unpack-objects failed
error: insufficient permission for adding an object to repository database ./objects
fatal: failed to write object
fatal: unpack-objects failed
Errors during submodule fetch:
	_themes/jekyll-theme-legumeinfo
	_themes/jekyll-theme-legumeinfo```

**Comment by adf-ncgr** [comment]
I think you have sudo so feel free to make such changes when needed in future but I've gone ahead and verified your suspicion and hopefully fixed it (at least for now):
```
[adf@dev-pb-jekyll jekyll-theme-legumeinfo]$ ls -ltr
total 72
-rw-rw-r--. 1 sdash developer 11357 Apr 29  2022 LICENSE
-rw-rw-r--. 1 sdash developer    69 Apr 29  2022 Gemfile
-rw-rw-r--. 1 sdash developer  5518 Apr 29  2022 CODE_OF_CONDUCT.md
-rw-r--r--  1 root  root      31746 Mar 19  2024 README.md
-rw-r--r--  1 root  root        853 Mar 19  2024 _config.yml
drwxrwxr-x. 2 sdash developer    60 Mar 19  2024 _sass
drwxrwxr-x. 6 sdash developer    53 Mar 19  2024 assets
drwxrwxr-x. 2 sdash developer  4096 Mar 19  2024 _includes
drwxrwxr-x. 2 sdash developer  4096 Mar 19  2024 _layouts
-rw-r--r--  1 root  root        737 Jun 24 11:40 jekyll-theme-legumeinfo.gemspec
[adf@dev-pb-jekyll jekyll-theme-legumeinfo]$ cd ..
[adf@dev-pb-jekyll _themes]$ ls
jekyll-theme-legumeinfo
[adf@dev-pb-jekyll _themes]$ sudo chown -R sdash:developer .
```

**Pull request merged**
